language: scala
jdk: openjdk8
before_install:
  - chmod +x gradlew
jobs:
  include:
    - stage: Compile-All-Versions
      script: ./gradlew compileScala211
    - script: ./gradlew compileScala212
    - script: ./gradlew compileScala213
    - stage: Test-All-Versions
      script: ./gradlew test211
    - script: ./gradlew test212
    - script: ./gradlew test213
    - stage: Publish-All-Versions
      script: ./gradlew publish211
    - script: ./gradlew publish212
    - script: ./gradlew publish213
